/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gbox2_DemoView */

#ifndef _Included_com_gbox2_DemoView
#define _Included_com_gbox2_DemoView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gbox2_DemoView
 * Method:    demo_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gbox2_DemoView_demo_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_gbox2_DemoView
 * Method:    demo_exit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gbox2_DemoView_demo_1exit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gbox2_DemoView
 * Method:    demo_draw
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gbox2_DemoView_demo_1draw
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gbox2_DemoView
 * Method:    demo_size
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_gbox2_DemoView_demo_1size
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_gbox2_DemoView
 * Method:    demo_move
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_gbox2_DemoView_demo_1move
  (JNIEnv *, jclass, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
