#!/bin/bash

make config PLAT=ios_armv6 DEBUG=$1 SDK="/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS$2.sdk" BIN='/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin'
make clean;make;make install

make config PLAT=ios_armv7 DEBUG=$1 SDK="/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS$2.sdk" BIN='/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin'
make clean;make;make install

rm -rf ./bin/ios_arm
mkdir ./bin/ios_arm
mkdir ./bin/ios_arm/inc
mkdir ./bin/ios_arm/lib
cp -r ./bin/ios_armv7/inc/gbox2 ./bin/ios_arm/inc/gbox2
lipo -create -arch armv6 bin/ios_armv6/lib/libgbox2.a -arch armv7 bin/ios_armv7/lib/libgbox2.a -output bin/ios_arm/lib/libgbox2.a
