
# make all
all : .null

# make install
install : .null

# make clean
clean : .null

# make update
update : .null

# make output
output : .null

# make error
error : .null

# make warning
warning : .null

# make doc
doc : .null

.null :

